# Generated by Django 4.1.5 on 2024-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('aadharNumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('userPic', models.CharField(max_length=150)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('userType', models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant')], max_length=50)),
            ],
        ),
    ]
