# Generated by Django 4.1.5 on 2024-05-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('houseId', models.AutoField(primary_key=True, serialize=False)),
                ('landLordId', models.IntegerField()),
                ('registerDate', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('cityName', models.CharField(max_length=60)),
                ('houseType', models.CharField(max_length=60)),
                ('houseName', models.CharField(max_length=60)),
                ('floorNumber', models.CharField(max_length=60)),
                ('numberOfBedRooms', models.CharField(max_length=60)),
                ('numberOfBathRooms', models.CharField(max_length=60)),
                ('squareFeet', models.CharField(max_length=60)),
                ('houseDescription', models.CharField(max_length=60)),
                ('utilitiesDescription', models.CharField(max_length=60)),
                ('houseImage', models.CharField(max_length=60)),
                ('nearByEmenities', models.CharField(max_length=60)),
                
                ('rentPrice', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'HouseDetails',
            },
        ),
    ]
